### ISSUE TITLE
Documentation clarification on supported graph flows

### ISSUE THREAD

**Issue by kinesii** [timekit-io/booking-js#168]
The readme says:

> At the time of writing, Timekit supports two graphs: instant and confirm_decline

But in https://github.com/timekit-io/booking-js/blob/master/examples/group-bookings.htm

I see: `bookingGraph: 'group_customer'`

Has graph flow support changed? As I would like to use `group_owner`

**Comment by laander** [comment]
@kinesii That line in the readme is out of date as we indeed do support group bookings now 🙈  

Here's some documentation, diagrams and guides on how group bookings work: http://developers.timekit.io/docs/graphs-flows

In booking.js, you can only use the `group_customer` graph and not the `group_owner`. The short explanation is that the `group_owner` graph is used to define slots for a resource (either through our API or our admin) and the `group_customer` represents each customer that signs up to the slot. The slots need to be defined in advanced in order to show them as bookable events in the calendar view. Does that makes sense?
