### ISSUE TITLE
Support RRULE (recurring events)

### ISSUE THREAD

**Issue by kfdm** [timekit-io/booking-js#39]
My google calendar has a lit of recurring events but it seems like they're ignored. Does bookingjs know how to read recurring events or does it only understand unique events?

**Comment by laander** [comment]
Hi @kfdm  

Booking.js uses the Timekit API to sync events with Google. If it encounters a recurring event, it treats each event instance as a regular event, thus the timeslot it occupies are considered busy in the FindTime (availability) algorithm.

From your description, it seems like this is not handled as expected. Could you send me an e-mail (la@timekit.io) with your Google email and a screenshot of the recurring events form the Google Calendar UI (or equivalent)? Then i can dig a bit :+1:

**Comment by kfdm** [comment]
Thanks. I've emailed you with the information. :)

**Comment by alialkhatib** [comment]
This is a similar but seemingly different question, so my apologies if it should be a separate issue - is it reasonable to extend bookings so that appointments are potentially recurring? I can think of a couple of use cases where it would be preferable to set recurring appointments every week or month (compared to manually booking every appointment).

I'm imagining a dropdown option in the booking form field giving options like ["once","weekly","monthly","annually"] or something (I imagine someone will make an argument for including "daily" but maybe we can hash that out or provide some options on the developer's side to expose frequencies).

**Comment by laander** [comment]
Moving the feature request by @alialkhatib to it's own thread (https://github.com/timekit-io/booking-js/issues/73) and closing this
