### ISSUE TITLE
All bookings end up on primary Google Calendar, despite configuration

### ISSUE THREAD

**Issue by zerosicks** [timekit-io/booking-js#90]
I'm using booking.js with a google account, and regardless of how I configure it, it only uses my primary google calendar to `findTime` and `createBooking`.

I'm not even sure this is an issue with Timekit, as the API tells me the bookings were created on the correct calendar. When I go into my google calendar however, all created bookings are just on my default google calendar.

As a test, I changed the calendar ID in my config to "frank". It actually still instantiated the calendar and `findTime` showed the availability of my default google calendar, but it wouldn't allow me to create new bookings due to the invalid calendar ID. 

The calendar I'm trying to use was created by a co-worker, but I've since been made the owner. As another test, I created a new calendar through `POST /calendars`, but using this new calendar's ID did not affect where my bookings end up. Again it allowed me to create bookings, the bookings show they're on the correct calendar when I ask Timekit's API, but when I look in my google calendar the appointments are on the default calendar.

We're thinking of just creating a new google account specifically for this booking as a workaround (so it has a clean calendar to pull from), but we had plans to use this on bigger projects so I'd like to find a better solution to this.

Here's my config:
```js
window.timekitBookingConfig = {
  "email":    'myemail@mysite.ca',
  "apiToken": 'my-api-token',
  "calendar": 'my-desired-calendar-id',
  "name":     'my-timekit-app-name',
  "timekitCreateBooking": {
    "event": {
      "calendar_id": 'my-desired-calendar-id' 
    }
  },
  "timekitFindTime": {
    "length": '15 mins',
    "calendars": ['my-desired-calendar-id'],
    "filters": {
      "and":[
        { "between_timestamps": {"start": "2016-03-30T10:00:00-07:00", "end": "2016-03-31T16:00:00-07:00", "timezone": "America/Los_angeles"}},
        { "specific_time": {"start": '10:15', "end": '15:45'}}
      ]
    }
  },
  "fullCalendar": {
    "slotDuration": '00:15:00',
    "minTime": '10:00:00',
    "maxTime": '16:00:00'
  }
};
```

When I `GET /calendars`:
```js
{
  "data": [3]
    0:  {
      "id": "my-default-google-calendar-id"
      "name": "myemail@mysite.ca"
      "display_name": "myemail@mysite.ca"
      "description": "My default google calendar"
      "foregroundcolor": "#1d1d1d"
      "backgroundcolor": "#9fe1e7"
      "created_at": "2016-03-23T12:11:32-0700"
      "updated_at": "2016-03-23T14:51:15-0700"
    },
    1:  {
      "id": "my-desired-calendar-id"
      "name": "mysite.ca_jibberish@group.calendar.google.com"
      "display_name": "mysite.ca_jibberish@group.calendar.google.com"
      "description": "The calendar I'm trying to book stuff on"
      "foregroundcolor": "#1d1d1d"
      "backgroundcolor": "#d06b64"
      "created_at": "2016-03-23T12:11:33-0700"
      "updated_at": "2016-03-23T14:51:15-0700"
    },
    2:  {
      "id": "timekit-created-calendar-id"
      "name": "mysite.ca_otherjibberish@group.calendar.google.com"
      "display_name": "Timekit Created Calendar"
      "description": "Another calendar created through Timekit's API"
      "foregroundcolor": "#1d1d1d"
      "backgroundcolor": "#ff7537"
      "created_at": "2016-03-23T14:40:46-0700"
      "updated_at": "2016-03-23T14:51:14-0700"
    },
}
```
And when I `GET /bookings`, it actually shows that the booking was created on the calendar I specified:
```js
{
  "id": "this-booking-id"
  "state": "confirmed"
  "graph": "instant"
  "completed": true
  "possible_actions": [0]
  "created_at": "2016-03-23T14:41:59-0700"
  "updated_at": "2016-03-23T14:42:02-0700"
  "attributes": {
    "event_info": {
      "what": "my-timekit-app-name x testbooking"
      "where": "TBD"
      "calendar_id": "my-desired-calendar-id"
      "description": "Comment: This should be on the right calendar..."
      "participants": [2]
        0:  "myemail@mysite.ca"
        1:  "myemail@mysite.ca"
      "start": "2016-03-30T12:15:00-0700"
      "end": "2016-03-30T12:30:00-0700"
    }
  }
  ...
}
```
One thing I noticed, is that when I `GET /accounts/google/calendars` there's an additional `primary` field that I don't see in [the example here](https://developers.timekit.io/docs/accountsgooglecalendars)
```js
0:  {
  "name": "Timekit Created Calendar"
  "description": "Another calendar created through Timekit's API"
  "synced": true
  "primary": null
  "property_key": "timekit-created-calendar"
},
1:  {
  "name": "myemail@mysite.ca"
  "description": null
  "synced": false
  "primary": true
  "property_key": "myemailmysiteca"
}
```

**Comment by laander** [comment]
Hi @sickslives, as far as i understand, the problem is two-fold:
1) Availability is found from the default calendar although a specific one has been chosen
2) Bookings end up in the wrong Google calendar although the API shows correct calendar

Let's start with 1)
The `timekitFindTime` config key can take the same settings as documented here https://developers.timekit.io/docs/findtime and you made a small typo when specifying your calendar: the key should be called `calendar_ids` instead of simply `calendars`. Furthermore, you would have to set a `emails: []` setting to an empty array to override the default behaviour of adding your email to the array.

**Comment by sickslives** [comment]
Hi @laander, thanks for the response!

While this problem is certainly manifesting in a two-foldly manner, I believe their root cause is the same.

I went ahead and simplified my config and corrected the typo:
```js
  window.timekitBookingConfig = {
    email:    'trevor@mysite.ca',
    apiToken: 'my-api-token',
    calendar: 'desired-calendar-id',
    timekitFindTime: {
      calendar_ids: ['desired-calendar-id']
    }
  };
```
This loads the widget with no errors and displays availability from my default google calendar, not my desired calendar.

If I add `emails: []` to my config as you suggest, `timekitFindTime` no longer sees the blocking activities on my calendar, but I'm the only user on both calendars, and I want my availability to be what shows in the booking widget, so that's not what I want.
If I add `user_ids: [my-user-id]` to that, it sees my availability again (still from the wrong calendar). The findTime documentation says `It will loop through all supplied users and look for timeslots that are free for all users.`, and it looks like the `emails: []` and `user_ids: []` options relate to the user availability, not which calendar to look at.

The [booking.js's github docs config example](https://github.com/timekit-io/booking-js#configuration) mention this:
```
calendar: '',   // Your Timekit calendar ID that bookings should end up in
```
And the further down, in [the timekitCreateBooking docs](https://github.com/timekit-io/booking-js#--timekitcreatebooking) it says this:
```js
timekitCreateBooking: {
  event: {    
    calendar_id:  config.calendar, // Inserted dynamically from the "calendar" setting in the general config
  },
},
```
Where does `timekitFindTime` look if no `calendar_ids` option is specified? I assumed it would also use the calendar specified in the general config, like `timekitCreateBooking` does. In testing it doesn't seem to matter if I include this option or not, bookings end up on my default calendar regardless. 

And yet when I query the timekit API it thinks the bookings went on the correct calendar. This is where I think the issue is, as timeKit thinks it's looking at the right calendar.

If you create a test google account and point booking.js at a calendar other than the default, does it work for you?

Do you know what that `primary: true` field indicates, and why it's not included in the [google calendars api example here?](https://developers.timekit.io/docs/accountsgooglecalendars) Is it new?

**Comment by sickslives** [comment]
Hi @laander, did you ever get a chance to look into this? We got around this originally by creating a separate google account per calendar, but we're running into more and more use cases where we'd like multiple calendars on the same google account.

**Comment by laander** [comment]
@zerosicks We actually deployed a fix recently that changes how bookings are saved in Google calendars. Before, the host were invited as a participant (using the email) on the event which resulted in the event also being saved in the primary calendar regardless. Now, the event is only saved on the specified calendar (the `calendar` key in the root if the config). 
Could you test it again?

We're currently investigating an issue with shared calendars, so you might be victim of that if it still doesn't work as expected. Hopefully we'll be able to deploy a fix by the beginning of next week.

Regarding the availability check, I'm still uncertain why that wouldn't work for you. To re-iterate, here's how the config should look like:
```
{
  timekitFindTime: {
    calendar_ids: ['your-cal-id-here'],
    emails: []
  }
}
```

If no `calendar_ids` are specified, the default is to take all the users' calendars into account, implicitly setting the config to this:

```
{
  timekitFindTime: {
    emails: ['your-email']
  }
}
```

**Comment by laander** [comment]
Btw if you're not loading booking.js from our CDN, make sure to update to `v.1.8.1` as that contains the fix 👍

**Comment by zerosicks** [comment]
Thanks @laander,
I am using the CDN, and the bookings now at least appear on the correct calendar. It seems however that now when I try to book bookings on that calendar it appears to fail, I still get the invite and a calendar appointment is created, but that spot doesn't get blocked out by `findTime`. That's another issue though so I'll close this.

**Comment by laander** [comment]
@zerosicks Glad the main problem got fixed! Do know that read-only calendars cannot be saved to and will throw an error. We're making some changes that will make this more obvious.

Could you write me on our Intercom chat in the admin panel (logging with the user you're having trouble with), then I can help you debug further 👍
